### ISSUE TITLE
No Data

### ISSUE THREAD

**Issue by sr45** [gbolabs/landisgyr-e230-reporter#4]
Hi, I use exactly the same parameters, but I get no data. After sending the request sequence I get /LGZ4ZMR120AC.K76 but nothing more. With the application of the ir reader I get the meter values, so the hardware seems to be ok. Do you have any tips for me?
kindly regards

**Comment by gboder** [comment]
Hi,

I remember having to be careful while sending the initial commands otherwise the emitter stood stuck and delivered some weird data back.

The [automatedread.py](https://github.com/gboder/landisgyr-e230-reporter/blob/main/src/python/automatedread.py) script from line 26 onwards is what I'm using now, with the waiting periods included. This sequence has been working fine for me for a while now.

Pay attention to line 11 as well where the serial port configuration is made. I do remember having troubles with the line endings `xonxoff ` and `rtsrcs`.

While hoping it helps...

Regards

Gautier
